
language: java

jdk:
- openjdk8

services:
    - mysql

before_install: 
    - mysql -uroot -e "grant all on belajar.* to belajar@localhost identified by 'java'"
    - mysql -uroot -e "drop database if exists belajar"
    - mysql -uroot -e "create database belajar"
    - mysql -uroot "belajar"
    - mysql -uroot -e "USE belajar;
      DROP TABLE IF EXISTS product;
      CREATE TABLE product (
          'id' varchar(32) NOT NULL,
          'code' varchar(10) NOT NULL,
          'name' varchar(255) NOT NULL,
          'price' decimal(19,2) NOT NULL,
          PRIMARY KEY ('d'),
          UNIQUE KEY 'code' ('code')
        ) ENGINE=InnoDB DEFAULT CHARSET=latin1;"
    - chmod +x mvnw
    - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('t4ufik83') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
    - sudo service mysql restart
after_success:
    - mvn jacoco:report coveralls:report
