
language: java

jdk:
- openjdk8

services:
    - mysql

before_install: 
    - mysql -uroot -e "grant all on belajar.* to belajar@localhost identified by 'java'"
    - mysql -uroot -e "drop database if exists belajar"
    - mysql -uroot -e "create database belajar"
    
after_success:
    - mvn jacoco:report coveralls:report
